version: '3.9'
services:

  nosql-db:
    image: mongo
    container_name: nosql-db
    ports:
      - "2717:27107"
    volumes:
      - mongo_db:/data/db

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server

  library:
    build:
      dockerfile: Dockerfile
      context: ./library
    container_name: library
    ports:
      - "4002:4002"
    environment:
      NODE_ENV: prod
    volumes:
      - ./library:/app/library
    restart: always
    depends_on:
      - nosql-db
      - redis

  user:
    build:
      dockerfile: Dockerfile
      context: ./user
    container_name: user
    ports:
      - "4001:4001"
    environment:
      NODE_ENV: prod
    volumes:
      - ./user:/app/user
      - /app/user/node_modules
    restart: always
    depends_on:
      - nosql-db

  gateway:
    build:
      dockerfile: Dockerfile
      context: ./gateway
    ports:
      - "4000:4000"
    depends_on:
      - library
      - user

volumes:
  mongo_db: {}
