# "uid": "65b78085fe37231b92bc04fa",
# "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkYWFhZGFkIiwiX2lkIjoiNjViNzgwODVmZTM3MjMxYjkyYmMwNGZhIiwiaWF0IjoxNzA2NTI0ODA2LCJleHAiOjE3MDY1MjY2MDZ9.60HeSZmJT0vnkX-aKBQ8QvzFI0xEH_tiTEANTkaeEcU",
# "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkYWFhZGFkIiwiX2lkIjoiNjViNzgwODVmZTM3MjMxYjkyYmMwNGZhIiwiaWF0IjoxNzA2NTI0ODA2LCJleHAiOjE3MDY2MTEyMDZ9.ANtfcnaReB1I7cuAUHFkzgZW1B4JT2o3xqDaITu_jxo"

POST http://localhost:4000/user 
Content-Type: application/json

{
    "name": "hahah"
}

###
GET http://localhost:4000/user/trial HTTP/1.1

###
Post http://localhost:4000/user/signup
Content-Type: application/json

{
    "email": "adaaadad",
    "password":"asd"
}

###
POST http://localhost:4000/user/renewtoken HTTP/1.1
Content-Type: application/json

{
    "uid":"65ad297fd3667ce22a73fd90",
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkc2RhYWFhZGFkIiwiX2lkIjoiNjVhZDI5N2ZkMzY2N2NlMjJhNzNmZDkwIiwiaWF0IjoxNzA1ODQ3MTY3LCJleHAiOjE3MDU5MzM1Njd9.AYibZ2ne2esCuVhTKcnXxEF39OVFVUJlNPX-jAzxEHU"
}

###
Post http://localhost:4000/user/signin
Content-Type: application/json

{
    "username": "MoThilak",
    "password":"12346789"


}

###
POST http://localhost:4000/user/transaction/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkZGFhYWRhZCIsIl9pZCI6IjY1YjM4NDUwYmYxN2FlNmI4OTA5OTZiZCIsImlhdCI6MTcwNjI2MzYzMywiZXhwIjoxNzA2MjY1NDMzfQ.iFAof8UM3-4eTFK8Fzarl9I6xse9EMPP83TaN2A0Pfw

{
    "amount": 500,
    "initiator": "65b38450bf17ae6b890996bd",
    "recipient":"65b38450bf17ae6b890996bd" 
}

#####################################################################  LIBRARY  #####################################################################



GET http://localhost:4000/book/book/menupage/77.608116/13.036693

###
GET http://localhost:4000/book/book/search/haha/77.608116/13.036693

###
GET http://localhost:4000/book/book/trial HTTP/1.1
    
###

POST http://localhost:4000/book/book/request-borrow
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1vaGFuLnRoaWxhazIxQGdtYWlsLmNvbSIsIl9pZCI6IjY1NTMwMzZkYWM1MmM4OGEyNmQ3NDA1OCIsImlhdCI6MTcwNjUyNTYxOCwiZXhwIjoxNzA2NTI3NDE4fQ.FFL_-5c5XqTn3r2MDhq8DylmgQOiQO4cajo6ZY8ZK5w

{
    "timestamp": 1699948872,
    "book_id": "65afaec3e97cda09b4650743"
}

###
GET http://localhost:4000/book/book/all

###
POST http://localhost:4000/book/book/add/65a36563aaa749d6cf771c1c HTTP/1.1
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkc2RhYWFhYWRhZCIsIl9pZCI6IjY1YTM2NGUwMzNmYmZjMjk3OWRlNWZjYSIsImlhdCI6MTcwNTIwNzAwOSwiZXhwIjoxNzA1MjA4ODA5fQ.t_oZ1FDujWk28wc6osxcUj3idcUUdhsMW37lTK0lM-w

{
    "name": "Blooming Dale",
    "author": "Rachel Green",
    "mrp": 225,
    "priceOfBorrowing": 12,
    "location": {
        "type": "Point",
        "coordinates": ["13.036693","77.608116"]
    }
}

###
GET http://localhost:4000/library/library/all

###
POST http://localhost:4000/library/library/create HTTP/1.1
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkc2RhYWFhYWRhZCIsIl9pZCI6IjY1YTM2NGUwMzNmYmZjMjk3OWRlNWZjYSIsImlhdCI6MTcwNTIwNzAwOSwiZXhwIjoxNzA1MjA4ODA5fQ.t_oZ1FDujWk28wc6osxcUj3idcUUdhsMW37lTK0lM-w

{
    "location": {
        "type": "Point",
        "coordinates": ["13.036693","77.608116"]
    },
    "name": "Budding Trees"
}

###
GET http://localhost:4000/library/library/find/13.036693/77.608116


###
GET http://localhost:4000/library/library/find/655318c0e90b5bcc77ba2bbe HTTP/1.1

### {
#     "_id": "64db5c27cf1cef5441b6af2a",
#     "name": "Budding Trees",
#     "owner": "64db3bb41480042c7a5d19bc",
#     "books": [],
#     "location": {
#     "type": "Point",
#     "coordinates": [
#         13.036693,
#         77.608116
#     ],
#     "_id": "64db5c27cf1cef5441b6af2b"
#     },
#     "revenue": 0,
#     "createdAt": "2023-08-15T11:06:15.670Z",
#     "updatedAt": "2023-08-15T11:06:15.670Z",
#     "__v": 0
# }



#####################################################################  NOTIFICATION  #####################################################################
GET http://localhost:5000/trial HTTP/1.1

###
GET http://localhost:8000/6553036dac52c88a26d74058

###
GET http://localhost:4000/notification


###
POST http://localhost:8000/razorpay/initiate-transaction
Content-Type: application/json

{
    "receipt": "das",
    "amount": 123321 
}