#  "uid": "657eec1a3928525dea6d02a2",
    # "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkc2RhYWFhYWFkYWQiLCJfaWQiOiI2NTdlZWMxYTM5Mjg1MjVkZWE2ZDAyYTIiLCJpYXQiOjE3MDI4MTY3OTUsImV4cCI6MTcwMjgxODU5NX0.OmDMrMQ84G4Co8wqgvjEInWC2rL2Dh0kFSd00cSItVk",
    # "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkc2RhYWFhYWFkYWQiLCJfaWQiOiI2NTdlZWMxYTM5Mjg1MjVkZWE2ZDAyYTIiLCJpYXQiOjE3MDI4MTY3OTUsImV4cCI6MTcwMjkwMzE5NX0.GKBClGhqmVwkhiu0BwtKD4bgw94QHG24wZ8-4ajgDwc",

POST http://localhost:4000/user 
Content-Type: application/json

{
    "name": "hahah"
}

###
GET http://localhost:4000/user/trial HTTP/1.1

###
Post http://localhost:4000/user/signup
Content-Type: application/json

{
    "email": "adsdaaaaadad",
    "password":"asd"
}

###
POST http://localhost:4000/user/renewtoken HTTP/1.1
Content-Type: application/json

{
    "uid":"655328ed47de7c25de56de16",
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik1vaGFuVGhpbGFrIiwiX2lkIjoiNjU1MzI4ZWQ0N2RlN2MyNWRlNTZkZTE2IiwiaWF0IjoxNjk5OTQ4NzgxLCJleHAiOjE3MDAwMzUxODF9.mYim8HICZbj2F93yvY8m8d0vqy04LoDt64Khgh04sa4"
}

###
Post http://localhost:4000/user/signin
Content-Type: application/json

{
    "username": "MoThilak",
    "password":"12346789"
}

#####################################################################  LIBRARY  #####################################################################



GET http://localhost:4000/book/book/menupage/77.608116/13.036693

###
GET http://localhost:4000/book/book/search/haha/77.608116/13.036693

###
GET http://localhost:4000/book/book/trial HTTP/1.1
    
###

POST http://localhost:4000/book/book/request-borrow
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkc2RhYWFhYWFkYWQiLCJfaWQiOiI2NTdlZWMxYTM5Mjg1MjVkZWE2ZDAyYTIiLCJpYXQiOjE3MDI4MTY3OTUsImV4cCI6MTcwMjgxODU5NX0.OmDMrMQ84G4Co8wqgvjEInWC2rL2Dh0kFSd00cSItVk

{
    "timestamp": 1699948872,
    "book_id": "655319a1e90b5bcc77ba2bc2"
}

###
GET http://localhost:4000/book/book/all

###
POST http://localhost:4000/book/book/add/65a36563aaa749d6cf771c1c HTTP/1.1
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkc2RhYWFhYWRhZCIsIl9pZCI6IjY1YTM2NGUwMzNmYmZjMjk3OWRlNWZjYSIsImlhdCI6MTcwNTIwNzAwOSwiZXhwIjoxNzA1MjA4ODA5fQ.t_oZ1FDujWk28wc6osxcUj3idcUUdhsMW37lTK0lM-w

{
    "name": "Blooming Dale",
    "author": "Rachel Green",
    "mrp": 225,
    "priceOfBorrowing": 12,
    "location": {
        "type": "Point",
        "coordinates": ["13.036693","77.608116"]
    }
}

###
GET http://localhost:4000/library/library/all

###
POST http://localhost:4000/library/library/create HTTP/1.1
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkc2RhYWFhYWRhZCIsIl9pZCI6IjY1YTM2NGUwMzNmYmZjMjk3OWRlNWZjYSIsImlhdCI6MTcwNTIwNzAwOSwiZXhwIjoxNzA1MjA4ODA5fQ.t_oZ1FDujWk28wc6osxcUj3idcUUdhsMW37lTK0lM-w

{
    "location": {
        "type": "Point",
        "coordinates": ["13.036693","77.608116"]
    },
    "name": "Budding Trees"
}

###
GET http://localhost:4000/library/library/find/13.036693/77.608116


###
GET http://localhost:4000/library/library/find/655318c0e90b5bcc77ba2bbe HTTP/1.1

### {
#     "_id": "64db5c27cf1cef5441b6af2a",
#     "name": "Budding Trees",
#     "owner": "64db3bb41480042c7a5d19bc",
#     "books": [],
#     "location": {
#     "type": "Point",
#     "coordinates": [
#         13.036693,
#         77.608116
#     ],
#     "_id": "64db5c27cf1cef5441b6af2b"
#     },
#     "revenue": 0,
#     "createdAt": "2023-08-15T11:06:15.670Z",
#     "updatedAt": "2023-08-15T11:06:15.670Z",
#     "__v": 0
# }



#####################################################################  NOTIFICATION  #####################################################################
GET http://localhost:5000/trial HTTP/1.1