# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
      RabbitMQ_URL: 1
      DefaultPort: 8000
      MongoURI: mongodb://mongodb:27017/test
      DBName: test

jobs:

  build:
    runs-on: ubuntu-latest
    services:
      mongodb:
          image: mongo
          env:
            MONGO_INITDB_DATABASE: test
          options: >-
            --health-cmd mongo
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          ports:
            - 27017:27017
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Test
      run: go test -v ./...
