# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
       image: mongo
       ports:
          - 27017:27017
       options: --name mongodb
    steps:
     - name: Checkout repository
       uses: actions/checkout@v2
       
     - name: Set up Go
       uses: actions/setup-go@v4
       with:
        go-version: '1.20'
        
     - name: List files in notification directory
       run: ls -R ./notification/internal/

     - name: Run tests
       env:
          RabbitMQ_URL: amqps://xpzfimfo:r9awQJBvXonsgv7YtXAgolBly1BrlwIf@puffin.rmq2.cloudamqp.com/xpzfimfo
          DefaultPort: 8000
          MongoURI: mongodb://mongodb:27017/test
          DBName: test
          
       run: |
         cd notification
         go test -v ./...
